spring:
  profiles:
    active: prod
springdoc:
  use-fqn: true
azure:
  storage:
    # all 3 of these values are needed for blob storage client to be auto-configured
    account-name: promogearsa
    account-key: npSOkSh9vCSXMsqkDpr2EYAOIePDNDM3KqdWYXetxKO81hSWebivWSqxqcE+gSuyIXSTsxhp5Ii0A3scH/v/9g==
    blob-endpoint: https://promogearsa.blob.core.windows.net/

  activedirectory:
    client-id: 61130a3e-2362-4c44-b86c-c840c0f32ea9
    tenant-id: 8ec578ae-91c9-4c17-b0ed-c2767953b320
    client-secret: cS67Q~crEh_NQJqKv~3Y~JLVrjqU~Db6kEjwt

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://psql-promo-gear.postgres.database.azure.com:5432/postgres?user=promogearadmin@psql-promo-gear&password=wR13mUPDNoznYz&sslmode=require
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
