spring:
  jpa:
    open-in-view: true
  profiles:
    active: prod
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 13b20fb1-7751-4ce4-ab35-5178f6ec731b
        credential:
          client-id: 858cfe4c-4558-49d8-b598-49eea8a6eee7
          client-secret: ~cn7Q~mEcpGMZf07Pn7n4bZAcP~2A3-jqyALQ

      storage:
        account-name: promogearsa
        account-key: npSOkSh9vCSXMsqkDpr2EYAOIePDNDM3KqdWYXetxKO81hSWebivWSqxqcE+gSuyIXSTsxhp5Ii0A3scH/v/9g==
        blob:
          endpoint: https://promogearsa.blob.core.windows.net/

springdoc:
  use-fqn: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://psql-promo-gear.postgres.database.azure.com:5432/postgres?user=promogearadmin@psql-promo-gear&password=wR13mUPDNoznYz&sslmode=require
    driver-class-name: org.postgresql.Driver
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
